name: CI
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Start InvisiRisk PSE
      uses: invisirisk/pse-action@main
      with:
        api_url: ${{ secrets.IR_URL }}
        app_token: ${{ secrets.IR_TOKEN }}
        mode: native
        collect_dependencies: 'true'
        workdir: ${{ github.workspace }}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: CI=true npm test -- --watch=false
    - name: Build app
      run: npm run build
on:
  push:
    branches:
    - master
  pull_request: null
  workflow_dispatch: null
